# Generated by Django 3.1.1 on 2020-09-04 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.FilePathField(path='/')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('managertype', models.CharField(choices=[('Sonarr', 'Sonarr'), ('Radarr', 'Radarr'), ('Lidarr', 'Lidarr'), ('LazyLibrarian', 'LazyLibrarian'), ('Mylar', 'Mylar')], max_length=20)),
                ('url', models.URLField()),
                ('apikey', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=25)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.downloadfolder')),
            ],
        ),
    ]
