# Generated by Django 3.1.1 on 2020-09-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadfolder',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/'),
        ),
    ]
