# Generated by Django 3.1.1 on 2020-09-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20200904_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadfolder',
            name='folder',
            field=models.CharField(max_length=400),
        ),
    ]
