# Generated by Django 3.1.1 on 2020-09-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20200904_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadfolder',
            name='folder',
            field=models.CharField(max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
