# Generated by Django 3.1.1 on 2020-10-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_downloader'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='downloadertype',
            field=models.CharField(choices=[('RTorrent', 'RTorrent'), ('SABNzbd', 'SABNzbd')], default='RTorrent', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloader',
            name='options',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
