# Generated by Django 3.1.1 on 2020-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20201010_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloader',
            name='options',
            field=models.JSONField(default={}),
        ),
    ]
