# Generated by Django 3.1.1 on 2020-10-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20201010_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloader',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
